app = "lenmoneybot-xxx"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python main.py"

[mounts]
  source="db_data"
  destination="/data"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
